version: '3.8'

services:
  web:
    build: ./webapp
    container_name: flask_app
    ports:
      - "8080:8080"
    environment:
#      WAIT_HOSTS: mongo:27017
#      MONGO_URI: mongodb://mongo:27017/mydatabase
      DOCKER_ENV: 1 #any value make it true
      CLIENT_ID: 35aedd448433476692a91887cd06e666
      CLIENT_SECRET: 6e312c190229470abfa68535d0480eb0
    volumes:
      - ./webapp:/app
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb:/data/db

volumes:
  db_data: