version: '3.8'

services:
  web:
    build: ./webapp
    container_name: flask_app
    ports:
      - "8080:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
      - DOCKER_ENV=1 #any value make it true
    volumes:
      - ./webapp:/app
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb:/data/db

volumes:
  db_data:
